// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// aggregate_vectors.cpp
cpp11::integers aggregate_vc(cpp11::integers grd, cpp11::integers mld, cpp11::writable::integers cst);
extern "C" SEXP _pointapply_aggregate_vc(SEXP grd, SEXP mld, SEXP cst) {
  BEGIN_CPP11
    return cpp11::as_sexp(aggregate_vc(cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(grd), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(mld), cpp11::as_cpp<cpp11::decay_t<cpp11::writable::integers>>(cst)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_pointapply_aggregate_vc", (DL_FUNC) &_pointapply_aggregate_vc, 3},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_pointapply(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
