// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// mytapply.cpp
cpp11::doubles mytapply_(cpp11::doubles  x, cpp11::doubles  y);
extern "C" SEXP _pointapply_mytapply_(SEXP x, SEXP y) {
  BEGIN_CPP11
    return cpp11::as_sexp(mytapply_(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles >>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles >>(y)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_pointapply_mytapply_", (DL_FUNC) &_pointapply_mytapply_, 2},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_pointapply(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
